# Form implementation generated from reading ui file 'FormLogIn.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

# QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True) # Scale the application depending on the screen resolution.


class Ui_FormLogin(object):
    def setupUi(self, FormLogin):
        FormLogin.setObjectName("FormLogin")
        FormLogin.resize(400, 558)
        FormLogin.setMinimumSize(QtCore.QSize(400, 558))
        FormLogin.setMaximumSize(QtCore.QSize(400, 558))
        FormLogin.setWindowTitle("")
        FormLogin.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(61, 61, 61);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=FormLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButton_3.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    color: White;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     color: Yellow;\n"
"}")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/lcs logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap("../Images/lcs logo.png"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap("../Images/lcs logo.png"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.On)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 50))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 450))
        self.frame.setStyleSheet("QFrame {\n"
"    border: 0px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: rgb(186, 186, 186);\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.txtUsername = QtWidgets.QLineEdit(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.txtUsername.setFont(font)
        self.txtUsername.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border-radius: 10px;\n"
"}")
        self.txtUsername.setObjectName("txtUsername")
        self.verticalLayout.addWidget(self.txtUsername)
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: rgb(186, 186, 186);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.txtPassword = QtWidgets.QLineEdit(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.txtPassword.setFont(font)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.verticalLayout.addWidget(self.txtPassword)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLogin = QtWidgets.QPushButton(parent=self.frame)
        self.btnLogin.setMinimumSize(QtCore.QSize(0, 40))
        self.btnLogin.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnLogin.setFont(font)
        self.btnLogin.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background: #FF1595;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background: #ED5AB3;\n"
"}")
        self.btnLogin.setObjectName("btnLogin")
        self.horizontalLayout.addWidget(self.btnLogin)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btnForgotPassword = QtWidgets.QPushButton(parent=self.frame)
        self.btnForgotPassword.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btnForgotPassword.setFont(font)
        self.btnForgotPassword.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    color: White;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     color: Yellow;\n"
"}")
        self.btnForgotPassword.setObjectName("btnForgotPassword")
        self.verticalLayout.addWidget(self.btnForgotPassword)
        spacerItem1 = QtWidgets.QSpacerItem(20, 160, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame)
        FormLogin.setCentralWidget(self.centralwidget)

        self.retranslateUi(FormLogin)
        QtCore.QMetaObject.connectSlotsByName(FormLogin)

    def retranslateUi(self, FormLogin):
        _translate = QtCore.QCoreApplication.translate
        self.label_3.setText(_translate("FormLogin", "La Camelle School"))
        self.label.setText(_translate("FormLogin", "Username"))
        self.label_2.setText(_translate("FormLogin", "Password"))
        self.txtPassword.setStyleSheet(_translate("FormLogin", "QLineEdit {\n"
"    padding: 5px;\n"
"    border-radius: 10px;\n"
"}"))
        self.btnLogin.setText(_translate("FormLogin", "Log in"))
        self.btnForgotPassword.setText(_translate("FormLogin", "Forgot password ?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_FormLogin()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())