# Form implementation generated from reading ui file 'FormHome.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 675)
        MainWindow.setMinimumSize(QtCore.QSize(1036, 675))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("padding: 0px;\n"
"margin: 0px;")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalGroupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.verticalGroupBox_3.setFont(font)
        self.verticalGroupBox_3.setStyleSheet("background-color: rgb(61, 61, 61);\n"
"padding: 0px, 0px, 0px;")
        self.verticalGroupBox_3.setObjectName("verticalGroupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalGroupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.verticalGroupBox_3)
        self.pushButton_5.setMinimumSize(QtCore.QSize(200, 30))
        self.pushButton_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setItalic(False)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: transparent;\n"
"    color: white;\n"
"    text-align: left;\n"
"    margin: 0px 0px 0px;\n"
"    padding: 0px 5px 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background: #5d5d5d;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/House-01.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_5.addWidget(self.pushButton_5)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.verticalGroupBox_3)
        self.pushButton_7.setMinimumSize(QtCore.QSize(200, 30))
        self.pushButton_7.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setItalic(False)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: transparent;\n"
"    color: white;\n"
"    text-align: left;\n"
"    margin: 0px 0px 0px;\n"
"    padding: 0px 5px 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background: #5d5d5d;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Images/list-color.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_5.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.verticalGroupBox_3)
        self.pushButton_8.setMinimumSize(QtCore.QSize(200, 30))
        self.pushButton_8.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setItalic(False)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: transparent;\n"
"    color: white;\n"
"    text-align: left;\n"
"    margin: 0px 0px 0px;\n"
"    padding: 0px 5px 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background: #5d5d5d;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Images/books-28.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_8.setIcon(icon2)
        self.pushButton_8.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_5.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.verticalGroupBox_3)
        self.pushButton_9.setMinimumSize(QtCore.QSize(200, 30))
        self.pushButton_9.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setItalic(False)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: transparent;\n"
"    color: white;\n"
"    text-align: left;\n"
"    margin: 0px 0px 0px;\n"
"    padding: 0px 5px 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background: #5d5d5d;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Images/05-bulb.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_9.setIcon(icon3)
        self.pushButton_9.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_5.addWidget(self.pushButton_9)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.verticalGroupBox_3)
        self.pushButton_6.setMinimumSize(QtCore.QSize(200, 30))
        self.pushButton_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setItalic(False)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: transparent;\n"
"    color: white;\n"
"    text-align: left;\n"
"    margin: 0px 0px 0px;\n"
"    padding: 0px 5px 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background: #5d5d5d;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Images/dumbell.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_5.addWidget(self.pushButton_6)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.verticalGroupBox_3)
        self.pushButton_12.setMinimumSize(QtCore.QSize(200, 30))
        self.pushButton_12.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(False)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: transparent;\n"
"    color: white;\n"
"    text-align: left;\n"
"    margin: 0px 0px 0px;\n"
"    padding: 0px 5px 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background: #5d5d5d;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Images/library-90.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_12.setIcon(icon5)
        self.pushButton_12.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_5.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.verticalGroupBox_3)
        self.pushButton_13.setMinimumSize(QtCore.QSize(200, 30))
        self.pushButton_13.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(False)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: transparent;\n"
"    color: white;\n"
"    text-align: left;\n"
"    margin: 0px 0px 0px;\n"
"    padding: 0px 5px 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background: #5d5d5d;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Images/product-data.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_13.setIcon(icon6)
        self.pushButton_13.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_5.addWidget(self.pushButton_13)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.btnUserName = QtWidgets.QPushButton(parent=self.verticalGroupBox_3)
        self.btnUserName.setMinimumSize(QtCore.QSize(200, 30))
        self.btnUserName.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.btnUserName.setFont(font)
        self.btnUserName.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: transparent;\n"
"    color: white;\n"
"    text-align: left;\n"
"    margin: 0px 0px 0px;\n"
"    padding: 0px 5px 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background: #5d5d5d;\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../Images/icon-user-7.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnUserName.setIcon(icon7)
        self.btnUserName.setIconSize(QtCore.QSize(24, 24))
        self.btnUserName.setObjectName("btnUserName")
        self.verticalLayout_5.addWidget(self.btnUserName)
        self.labelPosition = QtWidgets.QLabel(parent=self.verticalGroupBox_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelPosition.setFont(font)
        self.labelPosition.setStyleSheet("color: rgb(124, 124, 124);\n"
"padding: 5px, 5px, 0px;")
        self.labelPosition.setObjectName("labelPosition")
        self.verticalLayout_5.addWidget(self.labelPosition)
        self.line = QtWidgets.QFrame(parent=self.verticalGroupBox_3)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.verticalGroupBox_3)
        self.pushButton_10.setMinimumSize(QtCore.QSize(200, 30))
        self.pushButton_10.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: transparent;\n"
"    color: white;\n"
"    text-align: left;\n"
"    margin: 0px 0px 0px;\n"
"    padding: 0px 5px 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background: #5d5d5d;\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../Images/users-61.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_10.setIcon(icon8)
        self.pushButton_10.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_5.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.verticalGroupBox_3)
        self.pushButton_11.setMinimumSize(QtCore.QSize(200, 30))
        self.pushButton_11.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: transparent;\n"
"    color: white;\n"
"    text-align: left;\n"
"    margin: 0px 0px 0px;\n"
"    padding: 0px 5px 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background: #5d5d5d;\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../Images/settings-125.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_11.setIcon(icon9)
        self.pushButton_11.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_5.addWidget(self.pushButton_11)
        self.horizontalLayout.addWidget(self.verticalGroupBox_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("margin: 0px;\n"
"color: rgb(255, 85, 127);\n"
"padding: 0px;\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(18, 18, 18);")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(124, 124, 124);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(18, 18, 18);")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(18, 18, 18);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(124, 124, 124);")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(18, 18, 18);")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(124, 124, 124);")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(124, 124, 124);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("color: rgb(255, 85, 127);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(18, 18, 18);")
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_9.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(124, 124, 124);")
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_17.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(124, 124, 124);")
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 9, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 15, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_14.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(124, 124, 124);")
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 6, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(18, 18, 18);")
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 14, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(18, 18, 18);")
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 5, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_16.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(124, 124, 124);")
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 7, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_21.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(124, 124, 124);")
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 14, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_10.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(124, 124, 124);")
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(18, 18, 18);")
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 6, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_19.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(124, 124, 124);")
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 13, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_4.addItem(spacerItem3, 10, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(18, 18, 18);")
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 7, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(18, 18, 18);")
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 13, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_4.addItem(spacerItem4, 0, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(parent=self.groupBox_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_4.addWidget(self.line_4, 3, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(parent=self.groupBox_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(18, 18, 18);")
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 9, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(parent=self.groupBox_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_4.addWidget(self.line_5, 12, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(parent=self.groupBox_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_4.addWidget(self.line_6, 12, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(22, 22, 22);")
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 2, 0, 1, 2)
        self.label_24 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(22, 22, 22);")
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 11, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background: #0088cc;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background: #00aaff;\n"
"}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../Images/edit-60.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon10)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_4.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background: #7d3fbc;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background: #aa55ff;\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../Images/eye-21.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon11)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background: #1baf76;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background: #19bd4d;\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../Images/add-277.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon12)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background: #ff007f;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background: #ff557f;\n"
"}")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../Images/recycle-bin-32.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon13)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(150, 30))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("padding-left: 5px;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 1, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_4.addWidget(self.tableView)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_5.setText(_translate("MainWindow", "Home"))
        self.pushButton_7.setText(_translate("MainWindow", "Class list"))
        self.pushButton_8.setText(_translate("MainWindow", "Lesson"))
        self.pushButton_9.setText(_translate("MainWindow", "Quiz"))
        self.pushButton_6.setText(_translate("MainWindow", "Exercise"))
        self.pushButton_12.setText(_translate("MainWindow", "Sections"))
        self.pushButton_13.setText(_translate("MainWindow", "Reports"))
        self.btnUserName.setText(_translate("MainWindow", "Christopher"))
        self.labelPosition.setText(_translate("MainWindow", "Admin"))
        self.pushButton_10.setText(_translate("MainWindow", "Users"))
        self.pushButton_11.setText(_translate("MainWindow", "Utilities"))
        self.groupBox.setTitle(_translate("MainWindow", "Section Information"))
        self.label_8.setText(_translate("MainWindow", "null"))
        self.label_4.setText(_translate("MainWindow", "Girls:"))
        self.label_6.setText(_translate("MainWindow", "null"))
        self.label_5.setText(_translate("MainWindow", "null"))
        self.label.setText(_translate("MainWindow", "Section name:"))
        self.label_7.setText(_translate("MainWindow", "null"))
        self.label_2.setText(_translate("MainWindow", "No. of students:"))
        self.label_3.setText(_translate("MainWindow", "Boys:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Student Informaion"))
        self.label_11.setText(_translate("MainWindow", "null"))
        self.label_9.setText(_translate("MainWindow", "Last name:"))
        self.label_17.setText(_translate("MainWindow", "Gender:"))
        self.label_14.setText(_translate("MainWindow", "First name:"))
        self.label_22.setText(_translate("MainWindow", "null"))
        self.label_12.setText(_translate("MainWindow", "null"))
        self.label_16.setText(_translate("MainWindow", "Middle name:"))
        self.label_21.setText(_translate("MainWindow", "Password:"))
        self.label_10.setText(_translate("MainWindow", "Student Id:"))
        self.label_13.setText(_translate("MainWindow", "null"))
        self.label_19.setText(_translate("MainWindow", "Username:"))
        self.label_15.setText(_translate("MainWindow", "null"))
        self.label_20.setText(_translate("MainWindow", "null"))
        self.label_18.setText(_translate("MainWindow", "null"))
        self.label_23.setText(_translate("MainWindow", "Basic Information"))
        self.label_24.setText(_translate("MainWindow", "Login Details"))
        self.pushButton_3.setText(_translate("MainWindow", "Edit"))
        self.pushButton_4.setText(_translate("MainWindow", "Show password"))
        self.pushButton.setText(_translate("MainWindow", "Add"))
        self.pushButton_2.setText(_translate("MainWindow", "Delete"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Student Id"))
        self.comboBox.setItemText(1, _translate("MainWindow", "First name"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Last name"))

