DROP TABLE IF EXISTS CAI.TBL_STUDENT_INFO_ARCHIVE;
CREATE TABLE CAI.TBL_STUDENT_INFO_ARCHIVE (
    ARCHIVE_ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USERID UUID,
    SCHOOL_YEAR VARCHAR(9),
    STUDENTID VARCHAR(20),
    LASTNAME VARCHAR(50),
    FIRSTNAME VARCHAR(50),
    MIDDLENAME VARCHAR(50),
    SECTIONID INTEGER,
    PASSWORD TEXT,
    GENDER VARCHAR(50),
    PROFILE_PIC BYTEA,
    CONTACT_PERSON VARCHAR(255),
    CONTACT_NUMBER VARCHAR(20),
    -- Metadata columns
    ARCHIVED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ARCHIVED_BY VARCHAR(50) -- Optional: to track which admin performed the action
);
