DROP TABLE cai.tbl_answers;

CREATE TABLE cai.tbl_answers (
    answerid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assmt_key        INTEGER NULL, -- idkey, mckey, tfkey
    quiztype         VARCHAR(10) NULL,
    quiznumber       INTEGER NULL,
    itemno           INTEGER NULL,
    answer           VARCHAR(50) NULL,
    studentid        VARCHAR(50) NULL,
    datetaken        TIMESTAMP DEFAULT NULL,
    remarks          VARCHAR(50) NULL,
    CONSTRAINT unique_quiz_submission UNIQUE (quiztype, assmt_key, quiznumber, itemno, studentid)
);