DROP TABLE IF EXISTS CAI.TBL_STUDENT_INFO CASCADE;

CREATE TABLE CAI.TBL_STUDENT_INFO (
    USERID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID (),
    SCHOOL_YEAR VARCHAR(9),
    STUDENTID VARCHAR(20) UNIQUE,
    LASTNAME VARCHAR(50) NOT NULL,
    FIRSTNAME VARCHAR(50) NOT NULL,
    MIDDLENAME VARCHAR(50),
    SECTIONID INTEGER,
    PASSWORD TEXT,
    GENDER VARCHAR(50),
    PROFILE_PIC BYTEA,
    CONTACT_PERSON VARCHAR(255),
    CONTACT_NUMBER VARCHAR(20)
);

DROP SEQUENCE IF EXISTS cai.student_id_seq;
CREATE SEQUENCE cai.student_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999
    CYCLE;
